project:
  type: website
  output-dir: docs

website:
  title: "Máster en Ciencia de Datos"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: viz.qmd
        text: Visualizations

format:
  html:
    theme: cosmo
    toc: true
    embed-resources: false  # para websites no se necesita